remote_theme: pmarsceill/just-the-docs
search_enabled: true
title: Yeh Chan Yoo
description: A place for all my cool stuff
aux_links:
  "My LinkedIn Profile":
    - "//www.linkedin.com/in/yehchan-yoo/"
